
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-52-54-212-232.compute-1.amazonaws.com:5432/d3fm2osap6nrnv
    password: 75a838e20993724e28260f80b02e224e566f85ebafa9eb89468552e8056b68dd
    username: qnttyutmdjtwdr

  mvc:
    servlet:
      path: /api
jwt:
  secretKey: SupperKey
  expireTime: 864000000

